### ISSUE TITLE
MagicKeys-Agent crashes on El Capitan

### ISSUE THREAD

**Issue by benmeroff** [zsszatmari/MagicKeys#14]
MagicKeys-Agent crashes on start in El Capitan every time, even after removal and reinstallation.

Crash Details: http://pastebin.com/VPSeL1eS

**Comment by zsszatmari** [comment]
Thanks for reporting! I can't reproduce this, but I fixed it afaik, I will send you the fixed version tomorrow!

**Comment by benmeroff** [comment]
Thanks for getting on this so quickly!!

**Comment by zsszatmari** [comment]
You are welcome :) Please take a look at the version at https://www.dropbox.com/s/znp6723id0xsguo/MagicKeys.prefPane.zip?dl=0 . Let me know about the results!

**Comment by benmeroff** [comment]
That completely works!  No issues at all with 1.4.3, I've been using it with Radiant Player and it's right back to being as consistent as it was on Yosemite.

Thanks for the quick version update, great fix!

**Comment by zsszatmari** [comment]
Great to hear! Thanks for letting me know :+1:
