### ISSUE TITLE
Publish to AppStore

### ISSUE THREAD

**Issue by akokarev** [zsszatmari/MagicKeys#22]
Hi, good job!
I can't find this app at AppStore. But when I download it from website, at every startup I need allow application to run.
If it's free for all, can I send it to AppStore?
You can contact with me by email net-files at yandex dot ru

**Comment by zsszatmari** [comment]
Hi! Unfortunately, Apple does not allow this kind of low level functionality into the App Store, in fact, that’s why Magic Keys came into existence in the first place (so that Gear Music Player - which is an App Store application could have access to media keys)

**Comment by akokarev** [comment]
bad Apple
